FROM julia:1.11-bookworm

ENV JULIA_DEPOT_PATH=/opt/julia-depot

ENV DEBIAN_FRONTEND=noninteractive

RUN rm /var/lib/dpkg/info/libc-bin.* \
    && apt-get clean \
    && apt-get update \
    && apt-get install -y \
        git \
        wget \
        procps \
        clang \
        libblas-dev \
        liblapack-dev \
        libopenblas-dev \
        zlib1g-dev \
        r-base \
        r-base-dev

COPY . /opt/PostGWAS

RUN cd /opt/PostGWAS \
    && export R_HOME=/usr/lib/R \
    && julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'

RUN cd /opt/PostGWAS \
    && export R_HOME=/usr/lib/R \
    && julia --project --threads=auto -e 'using PackageCompiler; create_sysimage(:PostGWAS, sysimage_path="PostGWAS.so", include_transitive_dependencies=false, cpu_target=PackageCompiler.default_app_cpu_target())'

